### ISSUE TITLE
The execution order of meercat

### ISSUE THREAD

**Issue by walkingtospace** [walkingtospace/software_load_balancer#2]
For now, we should run the meercat in order of sysinfo, master and slaves.
It should be executed regardless of order freely.

**Comment by walkingtospace** [comment]
We've changed the hostChecker to be setInterval to solve this problem.

**Comment by Thalley** [comment]
The problem is still there. If you run 'node run master' first and then run 'node sysinfo', then the hostChecker either exits or just doesn't any response from sysinfo at all. 
The only change so far is that if you run 'node sysinfo' and then 'node run master' it doesn't work either.

**Comment by Thalley** [comment]
Didn't get your last update before trying. It seems to work now. I'm gonna start running an experiment on Emulab to check the correctness.

There is still a problem that if a sysinfo server disconnects (close the process) and then reconnect (run 'node sysinfo') again, it doesn't connect. This shouldn't be a big problem for us right now though.

**Comment by walkingtospace** [comment]
if a sysinfo server disconnects (close the process) and then reconnect (run 'node sysinfo') again, it doesn't connect. 
-> really? this problem still exist? please confirm that before closing this issue.

**Comment by Thalley** [comment]
I can confirm that this problem still exist. 
If everything is running and a host disconnects, the following line is printed at the LB (hostChecker):
[hostChecker] undefined disconnected

What further happens is:
- On disconnect, the disconnected server is not removed from the queue (if only sysinfo was closed and the webserver is still running, it can still send requests, but won't get information).
- When the sysinfo restarts after disconnect, it does not start sending data to the LB again

**Comment by walkingtospace** [comment]
Got it. I will on it.
