### ISSUE TITLE
The CPU usage measurement, "top -bn1"  doesn't give correct result.

### ISSUE THREAD

**Issue by walkingtospace** [walkingtospace/software_load_balancer#3]
top is not just "Measure stuff then output", we are running it with "top -bn1" which runs top and outputs the first frame. However, for some reason, the first frame of top is really bad... When the CPU usage is e.g. 80%, the first frame might report "30%" then the next frame shows "80%" 

(see http://unix.stackexchange.com/questions/190027/top-bn1-not-giving-correct-cpu-usage).

 We can run "top -bn2" to get the next (and correct frame), but this has a 1 second delay (waaaaaay too slow). So what I suggest is that we go back to using "ps aux" which will give us a result much faster, even though we have established that top is better.

**Comment by Thalley** [comment]
Fixed by using another CPU measurement
