### ISSUE TITLE
Single LB not supported

### ISSUE THREAD

**Issue by Thalley** [walkingtospace/software_load_balancer#6]
If we only have one load balancer where all the hosts are busy, it doesn't send the request anywhere, and the request is dropped. 

Similar, if all the other LBs are busy, then the request are dropped as well.

**Comment by walkingtospace** [comment]
For 1) I've added IF-ELSE statement to recognize whether the LB has a peer or not. If not, it just uses the first end-hosts.

For 2) I've added some code to work like the LB should redirect requests to its first end-host relentlessly if the LB gets an answer "NO" from all other LBs. (we have a buffer for that)

**Comment by Thalley** [comment]
Sorry for the late update (had to get an hour of sleep):
The problem unfortunately still seem to exist. The runtime for 20 requests is 5.4 seconds (no server is overloaded), but once the servers get overloaded, the runtime for 40 requests is 120 seconds. 
The output of the LB can be seen here: http://pastebin.com/vpueAY5Z

To make sure it works, please test with one LB and send enough requests to the servers so that they get overloaded
You can use the following command to test:
httperf --server 'IP of LB' --num-conn 40 --rate 40 --uri /compute
Assuming that a webserver.js is running on the hosts.

**Comment by walkingtospace** [comment]
By discussion, we've changed the code to use greedy algorithm (2-approximation)
